### ISSUE TITLE
Meta: v0.1.0

### ISSUE THREAD

**Issue by zsusswein** [CDCgov/cfa-gam-rt#1]
## Goal

Tracking the steps to an initial release. The goal is a minimum installable package. Useful but non-required functionality is pushed out to v0.2.0.

## Features

- [x] #5
- [x] #6
- [x] #7
- [x] #8
- [x] #9
- [x] #12
- [x] #30

**Comment by seabbs** [comment]
This looks good. Obviously point that you could use individual issues and a project workflow but this will work.

**Comment by seabbs** [comment]
I'm tempted to say once currents PRs are in that should be 0.1.0 release and then move all the tooling around that here to 0.2.0 (and move that to 0.3.0) etc

**Comment by kgostic** [comment]
Would it be possible to include a "getting_started" vignette or readme with 0.1.0? Other than that I'm supportive!

**Comment by zsusswein** [comment]
I want to hold the getting started vignette until we have some simulated data to fit to (#9). The readme should definitely make it though.

Thoughts on including the data + vignette or bumping?

**Comment by kgostic** [comment]
I don't have strong opinions -- I think this depends on whether the goal of the release is to have something for _you_ to pin to, or for others to use/follow

**Comment by seabbs** [comment]
Yeah exactly. I would vote go as it's nice to have something to pin to and point to say this is the initial idea but if the plan is to send it to users we should wait.
