### ISSUE TITLE
epinowcast universe use

### ISSUE THREAD

**Issue by seabbs** [CDCgov/cfa-gam-rt#102]
https://github.com/CDCgov/cfa-gam-rt/blob/15c14804c7dbca9ad5e67f1796066eca1731589f/DESCRIPTION#L52

What is this for at the moment? The only thing I think I see is `primarycensored` and it feels like we may as well use the CRAN version (perhaps this is just out of date)?

**Comment by zsusswein** [comment]
Just out of date. It's from pre-CRAN.
