### ISSUE TITLE
Flaky pre-commit checks in GHA as a post-push hook

### ISSUE THREAD

**Issue by zsusswein** [CDCgov/cfa-gam-rt#24]
When running in GHA, pre-commit randomly struggles to find `{styler}` and errors out. @kaitejohnson has also seen this in some of the wastewater work and potentially has a suggested fix.

**Comment by kaitejohnson** [comment]
Testing this out [here](https://github.com/CDCgov/wastewater-informed-covid-forecasting/pull/141) now. @dylanhmorris and I believe Jason and Scott helped me debug this when switching from the repo template internally to pre-commit from GH actions. I think the key this is that we set up the style-files with args pointing to `styler`. 

It looks like in the public repo we actually hadn't been running pre-commit hooks!
```
        args: [--style_pkg=styler, --style_fun=tidyverse_style,
               --cache-root=styler-perm]
    -   id: use-tidy-description
    -   id: lintr
    -   id: readme-rmd-rendered
    -   id: parsable-R
    -   id: no-browser-statement
    -   id: no-print-statement
    -   id: no-debug-statement
    -   id: deps-in-desc
        exclude: data-raw
```

https://github.com/CDCgov/wastewater-informed-covid-forecasting/pull/141
