### ISSUE TITLE
Readme: v0.1.0 release updates

### ISSUE THREAD

**Issue by zsusswein** [CDCgov/cfa-gam-rt#30]
And related pre-release cleanup.

- [x] Fix RtGam return docs
- [x] RtGAM -> RtGam in readme title
- [ ] More citations in readme
- [ ] ~~.bib?~~
- [x] Parallel descriptive language for `*_dim_heuristic()`
- [x] Latex equation in RtGam
- [x] Note in Methods definition

**Comment by seabbs** [comment]
>  More citations in readme 

new issue?
