### ISSUE TITLE
v0.3.0: Day-of-week effects

### ISSUE THREAD

**Issue by zsusswein** [CDCgov/cfa-gam-rt#4]
## Goal

Add usage and testing for day-of-week effects

## Features

- [x] #40
- [x] #90
- [x] #87
- [x] #92

**Comment by seabbs** [comment]
> Right-truncation correction 

I really liked Chris's approach here to estimate the delay elsewhere and then use it as an offset. I think the slightly better version is to still also fit a non-parametric delay to allow it to slightly vary etc but it seems like a really nice way of enforcing a bit of mechanism into these very flexible models.

**Comment by zsusswein** [comment]
https://github.com/CDCgov/cfa-gam-rt/releases/tag/v0.3.0
