### ISSUE TITLE
Update lazyload dataset name in readme

### ISSUE THREAD

**Issue by zsusswein** [CDCgov/cfa-gam-rt#43]
The name of Katie's "Practical considerations" dataset got updated on review to `stochastic_sir_rt`. It's still under the original proposed name in the readme:

https://github.com/CDCgov/cfa-gam-rt/blob/0e831380a2c0a8ec63219781226e32e013093f38/README.md?plain=1#L39-L46

**Comment by seabbs** [comment]
Also worth exploring why that slipped through/how to avoid a repeat going forward

**Comment by zsusswein** [comment]
My gut reaction is that this kind of thing should be handled by an Rmd (or qmd) readme that renders in GHA or a vignette. Either/both would have caught this and allow a more full-featured walkthrough. Let's revisit in #44.

**Comment by seabbs** [comment]
yes agree
