### ISSUE TITLE
Getting started vignette

### ISSUE THREAD

**Issue by zsusswein** [CDCgov/cfa-gam-rt#44]
Both as a full vignette and perhaps building out the how-to in the Readme. If expanding the readme, consider moving the a Rmd readme that renders in GHA.

**Comment by seabbs** [comment]
I used to really like how tos in the README but multiple devs I have worked with have pushed to keep it very sparse and signposted and to have the code getting started be in a specific place

**Comment by zsusswein** [comment]
I'm surprised to hear that. R culture is pretty vignette-oriented. But see e.g., [ripgrep](https://github.com/BurntSushi/ripgrep), [ruff](https://github.com/astral-sh/ruff), or [duckdb](https://github.com/duckdb/duckdb). I'd think a lightweight readme to help potential uses identify whether reading the vignette would be worth it is a good idea?

**Comment by seabbs** [comment]
I'm not disagreeing it isn't something people do I am just pointing out a counter view which I have seen a lot recently in epi silos. I think both are valid choices.

**Comment by SamuelBrand1** [comment]
Hey @zsusswein  This project looks super interesting.

I'd love to see a full featured getting started vignette; or a simpler one and a more "in the weeds" example. It would help as an entry point for people having a glance (i.e. me).

**Comment by zsusswein** [comment]
I'm working on it for the v0.2.0 release! I'm hoping to have that out this week.

Or in other words, ask and you shall receive...
