### ISSUE TITLE
Enable dependabot

### ISSUE THREAD

**Issue by zsusswein** [CDCgov/cfa-gam-rt#54]
Enable dependabot following @seabbs implementation here: https://github.com/epinowcast/epinowcast/pull/354

As far as I can tell, this is only to keep GHA's deps up to date and can't handle R dependencies.

**Comment by seabbs** [comment]
yes correct. Python just got support so we can dream of R also getting support. I am unaware of anything in the R ecosystem that does this for you (i.e like CompatHelper.jl in Julia) but also the R ecosystem makes a point to be more stable and so these issues are much rarer (no packages I have developed have been broken by upstream changes without plenty of warning I could have acted on)
