### ISSUE TITLE
Simulated data from Gostic, 2020

### ISSUE THREAD

**Issue by zsusswein** [CDCgov/cfa-gam-rt#9]

**Comment by zsusswein** [comment]
@seabbs I'm thinking about setting up some simple benchmarking on CI as part of this issue. Thoughts? Is it worth the lift at this early point?

If yes, do you have a template or PR floating around where you implemented this for EpiAware or epinowcast?

**Comment by seabbs** [comment]
I find it really useful. That being said as so much of the modelling is from `mgcv` it feels like we are less likely to be making changes that introduce performance issues and so maybe this is less of a focus at this stage?



We use `{touchstone}` which can be a major! pain. See here for `epinowcast`: https://github.com/epinowcast/epinowcast/pull/200

**Comment by zsusswein** [comment]
I'm less concerned about benchmarking runtime and more about benchmarking predictive error (maybe this should just be an end to end test?). I can see a world where a "clever" change degrades performance and I want to catch it early.

**Comment by seabbs** [comment]
I feel like that is part of unit testing vs benchmarking?
