### ISSUE TITLE
Use dev version whilst in dev

### ISSUE THREAD

**Issue by seabbs** [CDCgov/cfa-gam-rt#99]
https://github.com/CDCgov/cfa-gam-rt/blob/a7ced361bc177bcc52faf8e2578b40b9d31826b1/DESCRIPTION#L3

Noticed whilst looking at #85. We should really be using a dev version whilst in dev. This would help with automating dev and release docs in pkggdown (via the auto deploy mode).

**Comment by zsusswein** [comment]
What does this mean in practice? Always bump to 0.x.0 then bump to 0.x.1000 immediately after release? Or release at 0.x.1000 to signify that this is a package with no stability guarantees?

**Comment by seabbs** [comment]
> Always bump to 0.x.0 then bump to 0.x.1000 immediately after release?

This

**Comment by seabbs** [comment]
but rather `0.x.0.1000`
